---
- name: install apt tools
  apt:
    name: "{{ item }}"
  loop:
    - default-jdk
    - openjdk-11-jdk
    - openjdk-17-jdk
    - maven
- name: install snap tools
  community.general.snap:
    name: "{{ item }}"
    classic: yes
  loop:
    - intellij-idea-ultimate
